Resources:
  N8NDBPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}/${self:provider.stage}/rds-master-password
      Description: "RDS master password for n8n"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "n8nadmin"}'
        GenerateStringKey: "password"
        PasswordLength: 32
        ExcludeCharacters: '"@/\\`'
      Tags:
        - Key: Name
          Value: ${self:service}-${self:provider.stage}-rds-master-password-secret

  N8NEncryptionKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}/${self:provider.stage}/n8n-encryption-key
      Description: "n8n encryption key (user to populate with strong random string)"
      GenerateSecretString:
        SecretStringTemplate: '{"key": ""}'
        GenerateStringKey: "key"
        PasswordLength: 32
        ExcludeCharacters: '"@/\\`'
      Tags:
        - Key: Name
          Value: ${self:service}-${self:provider.stage}-encryption-key-secret

  N8NSmtpPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}/${self:provider.stage}/smtp-password
      Description: "SMTP password for n8n (user to populate if SMTP auth is used)"
      GenerateSecretString:
        SecretStringTemplate: '{"password": ""}'
        GenerateStringKey: "password"
        PasswordLength: 32
        ExcludeCharacters: '"@/\\`'
      Tags:
        - Key: Name
          Value: ${self:service}-${self:provider.stage}-smtp-password-secret
